services:
  app:
    build:
      dockerfile: docker/Dockerfile
      context: ../
      target: development
    # volumes:
    #   - ../:/app
    env_file:
      - .env
    command: npm run start:dev
    ports:
      - 3000:3000
    depends_on:
      - db
      - redis

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - docker-nest-postgres:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data

  dbadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: 'admin@admin.com'
      PGADMIN_DEFAULT_PASSWORD: 'admin'
    ports:
      - '5050:80'
    depends_on:
      - db
volumes:
  redis:
    driver: local
  docker-nest-postgres:
